### ISSUE TITLE
Plugin couldn't be activated due to fatal error

### ISSUE THREAD

**Issue by spinozarabel** [celtic-project/wordpress-lti#10]
Hi,
Firstly, thank you for your generosity in making this publicly available.

I am using WP 5.6. I had been using your ver 1.2 with modifications for SSO and that still works flawlessly.

I wanted to upgrade to the latest LTI with a view to ensure compatibility incase of deprecations in software.
I cloned the repository and from the /plugins/lti directory performed a composer install. This installed libraries w/o errors.
I didn't try to create any new MYSQL tables thinking that the network activation would do all of it.

When I try to network activate the plugin I get the following error:

Warning: require_once(/var/www/html/sritoni.org/public_html/wp-content/plugins/lti/config.php): failed to open stream: No such file or directory in /var/www/html/sritoni.org/public_html/wp-content/plugins/lti/includes/lib.php on line 34

Now I don;t see a config.php, I only see a config-dist.php and this too has some keys etc which seem to be needed. I am a bit confused as to what to do next. 
Also, in digging deeper using the error message above, I notice that in line 34 on lib.php it says:
use ceLTIc\LTI\Platform;
use ceLTIc\LTI\ResourceLink;
use ceLTIc\LTI\Util;

However, the classes are defined under /celtic/lti/src. I wonder if this could be a problem?

Any help will be vastly appreciated. Kind regards, Madhu

**Comment by spvickers** [comment]
Did you follow the "Updating the plugin" instructions in the Installation section of the documentation.  The latest releases also require a config.php file which should be created (you can use the config-dist.php file as a basis); sorry, this is missing from the documentation, I shall add it.

**Comment by spinozarabel** [comment]
Indeed I did. I deleted the old plugin first and removed all its tables. Then I cloned the repo and performed a composer install in the lti plugin's directory and it installed the dependencies. I then try to activate and get the error. I did see that the dependency installation and lib callout for the classes directory structure don't match. there is an extra src subdirectory in there as I mentioned originally.

**Comment by spvickers** [comment]
The src directory should not be an issue.  According to the error you reported, the problem appears to be caused by the missing config.php file.  Have you tried adding this?

**Comment by spinozarabel** [comment]
I did. I copied the config-dist.php to config.php (exact replica). **Now the plugin network activates without error** and I can proceed to next step. Do I need to something about the RSA key? What is that for?

**Comment by spvickers** [comment]
The RSA key is used for signing requests for an access token when using LTI 1.3.

**Comment by spvickers** [comment]
Documentation updated to include details of the config.php file when installing the plugin.
