### ISSUE TITLE
Plugin is activating but nothing in menu

### ISSUE THREAD

**Issue by Luna9SA** [celtic-project/wordpress-lti#11]
Hey there,

Firstly thank you for making this public.

I have followed the installation process using composer. I have updated the config file as you have shown. The issue here is that I have activated the plugin however do not have "LTI Platforms" on the menu. Below is info from config file.

define('LTI_ID_SCOPE_DEFAULT', NONE);
define('LTI_LOG_LEVEL', Util::LOGLEVEL_NONE);
define('LTI_SIGNATURE_METHOD', 'NONE');
define('LTI_KID', 'NONE');  // A random string to identify the key value
define('LTI_PRIVATE_KEY', <<< EOD
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
EOD
);

###
###
define('AUTO_ENABLE', false);
define('ENABLE_FOR_DAYS', UNLIMTED);
?>

**Comment by spvickers** [comment]
Are you looking at the Network Admin menu, rather than a Site Admin menu?  Have you tried setting the log level to Util::LOGLEVEL_ERROR or Util::LOGLEVEL_DEBUG to see if any errors are reported?  What version of WordPress are you using?

**Comment by Luna9SA** [comment]
Thank you for the quick response, Im using site admin menu. I have tried both log levels and seen no errors. I am running wordpress 5.8.1

**Comment by spvickers** [comment]
The "LTI Platforms" item appears on the network admin menu, not on the site admin menus.  That explains why you are not seeing it.

**Comment by Luna9SA** [comment]
My site isnt a multi site though

**Comment by spvickers** [comment]
This plugin is designed for multisite versions of WordPress.

**Comment by Luna9SA** [comment]
So in order to use this I would need to convert the site into a multisite?

**Comment by Luna9SA** [comment]
Is there a reason for that?

**Comment by spvickers** [comment]
The plugin creates a new site for each LTI resource link from which it is launched; in this way they are kept separate from each other.  Hence the need for the multisite installation.
