### ISSUE TITLE
Issue with "Save Changes" - LTI Plugin "Options"

### ISSUE THREAD

**Issue by pacesetter-cm** [celtic-project/wordpress-lti#12]
Hi, 

I was able to get this plugin installed (using your instructions for Composer, on a shared host at Siteground), and I am able to create new platforms using the plugin. 

I am trying to remove the plugin so I can reinstall it on another site that doesn't have other plugins interfering with the login process; however, _**when I try to manage the settings to "Delete all data" etc., I am unable to "Save Options".**_  

![lti-options](https://user-images.githubusercontent.com/96441643/146815698-1459f1af-5bc8-4bba-b1e5-2c3ddb484f80.png)

When attempting to save options, it goes to an "insecure page warning" before submitting. When I choose to "submit anyway", it gives the error that I don't have sufficient permission. This is a superadmin user, who should have the required permissions (like "manage_network_options"). 

Is there a way I can fix this error to be able to remove anything that was put in the database when the plugin is uninstalled?

![permission-error](https://user-images.githubusercontent.com/96441643/146815790-82f3d7df-4a71-42cd-aa05-f6f039499a0c.png)

Should the plugin still work with the current version of Wordpress? I am not very familiar with LTI and still have to learn how to use it; I am hoping this can be used for connecting Wordpress Multisite with any LTI-enabled virtual learning environment? 

Thank You!

**Comment by spvickers** [comment]
I am not able to replicate this issue when checking the "Delete all data" option and saving the form.  Which version of the plugin are you using?  Do you get the same message when you try saving the form without checking this option?  Have you tried a different browser to see if the same issue arises?  Are you running WordPress with https (though I have tested with both http and https and been unable to replicate the issue).  (Note that my tests were with WordPress 5.8.2.)

**Comment by pacesetter-cm** [comment]
Thank you for the quick reply!

Yes, I am also on 5.8.2. I tried all different options, or no options, and saving the form creates the same issue. 

I found that when I turn off ssl (which is managed by a SiteGround plugin called "SG Optimizer"), then it allows me to save options. I have also noticed an error after turning on logging that I think is related to the plugin:

"
Notice: Undefined index: adduser in /home/customer/www/paceware.us/public_html/wp-content/plugins/lti/lti.php on line 542

Warning: Cannot modify header information - headers already sent by (output started at /home/customer/www/paceware.us/public_html/wp-content/plugins/lti/lti.php:542) in /home/customer/www/paceware.us/public_html/wp-includes/functions.php on line 6712
"

Is there a certain way to set up ssl so it can work through ssl? I can try changing the way the ssl is done if you think this might be necessary.

I also have another site set up, where I will try to install Wordpress-lti first. 

Is there a recommended tool I can use to emulate the "LTI Platform"? I have found a couple but am new to LTI and not sure which of these is best or reliable. I am trying to use this plugin to connect with a proprietary VLE which is set up to use LTI 1.1. 

Thank you again!

**Comment by spvickers** [comment]
Have you tried using a different browser to see if you still have the same issue?  I suspect that this might be caused by the security settings of the browser. If not, it sounds like it might be the SSL configuration of your server.  I am not familiar with the SG Optimizer plugin; in my own case I simply have an SSL certificate installed on the server.

For testing purposes, I recommend that you look at saLTIre also provided from the ceLTIc Project - see https://saltire.lti.app.  This service supports the emulation of both platforms and tools with all versions of LTI.

**Comment by pacesetter-cm** [comment]
Hi again, and thank you again for your help.

I found that the SSL configuration seems to be what is causing the problem(s) I was having with saving the plugin options. I also noticed Firefox browser seems to work better than chrome, with all caching turned off. I uninstalled it and reinstalled with SSL turned off and it seems to be working now. 

I was also able to get that tool you suggested to connect successfully! 

It seems I still need to learn more about how to set up the courses/resources so that I am creating the right user roles (I have only gotten it to work so far with the config set to "GLOBAL"; this created a new site under "my sites", and created the user as the only user, as admin, on that site. It has the same URL except including the consumer key.)

If I understand correctly, I should have a separate site maintained (with unique consumer key in URL) for each individual platform that will connect. In the LTI tools, how can I find how to connect future sign in requests for this platform with the same site and course content?

I am using a plugin called Learndash (LMS plugin). It creates custom post types for courses, lessons, tests, classes, etc, each of which have a wordpress post ID. In the LTI tool options, does "Resource Link" correlate with a page or post ID?

I assume the type should be "course offering", but I am also confused by the parameters "course offering sourcedid" and "course section sourcedid"

![lti-context_resource](https://user-images.githubusercontent.com/96441643/147506801-ae85214c-2e29-4d12-a7aa-2f7e4c572fa9.png)

Thank you again. For all your help. It is installed and working, and the LTI tool has connected successfully. Now I just need to get it to connect to resources that are already built (as opposed to creating new resources on the site).

We are trying to use this to connect to a VLE where only students will be logging in....there are many different options and parameters I need to learn I think!

**Comment by spvickers** [comment]
Glad to learn that you have resolved the issue.

The terms "resource link", "course offering" and "course section" all come from the IMS specs for LTI and LIS.  A resource link is essentially the link added within the LMS which is clicked by a user to launch into an LTI tool.  This plugin is designed to associate each resource link with a separate blog within WordPress.  The username scope can be set to restrict access for a user to this single blog (by creating a separate user account for each user and resource link combination), or to implement more relaxed access permissions.  The current version of the plugin is not designed to connect a user to existing content within WordPress, although I am currently working on an update to support non-multisite installations which may better fit your needs.  Feel free to submit another issue outlining your use case in more detail and I will see whether this can be accommodated.  In the meantime, I suspect you will need to either adapt the code yourself (e.g. the onLaunch method of the WPTool class), or create your own subclass of the Tool object to implement the required behaviour.

**Comment by pacesetter-cm** [comment]
Thank you again for all the extra help. 

That's great you are working on an update for single site WordPress installations. This is something we would be very interested in, as we need to connect new users from an LTI-enabled virtual learning environment to existing resources (courses, groups, etc) in our WordPress application.

I will do as you suggest and open another issue with more details.

Thanks again!
