### ISSUE TITLE
Add LTI Advantage - Auto configuration

### ISSUE THREAD

**Issue by martinsam** [celtic-project/wordpress-lti#14]
From Moodle, There is an action "Add LTI Advantage". 

It seems something is missing. 
LTI plugin and LTI tools plugins are installed. I use the following url:  <my_own_domain>/?lti-tool into  Moodle. So, The interface that loads in the iframe is unusable
![Capture d’écran 2022-03-23 à 18 03 14](https://user-images.githubusercontent.com/34697/159757284-4bdff459-6299-4d46-a05a-dd26f8c696ff.png)

**Comment by spvickers** [comment]
Thanks for reporting this.  It is the victim of some refactoring when releasing version 3.  The committed changes should resolve it.
