### ISSUE TITLE
[ERROR] Request failed with reason: 'Username may not be longer than 60 characters.

### ISSUE THREAD

**Issue by kenwrick** [celtic-project/wordpress-lti#17]
I updated a dormant install of WP that had wordpress-lti installed in the past, upgraded it to WP 6.1.1, installed the latest version of the plugins, set the theme from 2023 to 2019.  When I try to connect the debug log lists:

[ERROR] Request failed with reason: 'Username may not be longer than 60 characters.

I altered the wp_user table user_login varchar(255), but I'm still getting that error.  Do I need to modify WP code or is it ID that the error is reporting?

**Comment by spvickers** [comment]
I think you will find that this error is being generated by WordPrress.

**Comment by kenwrick** [comment]
Thanks.
