### ISSUE TITLE
Convert launch url from http to https

### ISSUE THREAD

**Issue by edzai** [celtic-project/wordpress-lti#19]
SOrry, had posted in the wrong repo. Hi, I am using the the plugin wordpress-lti (as provider) and am trying to connect to Moodle (as consumer). The problem I am facing is that the wordpress plugin is generating http instead of https for the launch url. How do I change the http to https in the launch url?

**Comment by spvickers** [comment]
The launch URL used is defined in Moodle, this plugin merely processes the LTI message sent by Moodle.  Check the tool configuration in Moodle to make sure it is using https for the message URL.

**Comment by edzai** [comment]
<img width="968" alt="Screenshot 2023-03-14 at 12 23 14" src="https://user-images.githubusercontent.com/10413942/224971138-71df3bb3-c8cf-4e78-a3dd-a48c83cfcece.png">
It is being generated by Wordpress as shown in the screenshot. Once I get the Launch url, secret and key then I got to Moodle to add the external tool.

**Comment by spvickers** [comment]
Is your WordPress running on https?  If so, is it behind a load balancer which is offloading the https traffic so that the web server only sees http?

The quick workaround here is to just ignore the http here and configure Moodle with https if it is supported.

**Comment by spvickers** [comment]
Please re-open this issue if you have not been able to resolve it.  Hopefully it was just an SSL offloading problem.
