### ISSUE TITLE
LTI Platforms admin menu page capability

### ISSUE THREAD

**Issue by zigasancin** [celtic-project/wordpress-lti#22]
Hello,
I found out that you're using the `edit_plugins` capability when [defining the admin menus](https://github.com/celtic-project/wordpress-lti/blob/master/lti-tool.php#L232-L271). According to the [official docs](https://developer.wordpress.org/apis/wp-config-php/#disable-the-plugin-and-theme-file-editor), this should be avoided. A lot of managed hosting companies as well as popular security plugins like Shield enforce this directive.

I propose switching these usages to a custom filter with a default priority that would use `manage_options` / `manage_network_options` capability as the default and this would also allow overrides by users who may want to assign a custom capability.

Just wanted to get some feedback before I create a PR.

Thanks!

**Comment by spvickers** [comment]
Thanks I'll take a look at this and make any necessary updates.

**Comment by spvickers** [comment]
Looks like it might be better to change the capability to activate_plugins instead.  Do you see any issues with this?

**Comment by spvickers** [comment]
Or are you suggesting that the access to managing the list of LTI platforms might need to be given to someone who does not have access to the plugins area at all?

**Comment by zigasancin** [comment]
Well, there are two things that this change would fix:
1) hosting environment and plugin conflicts by providing a better default capability
2) allow the community to filter the capability if they use custom capabilities for specific WP Admin features or settings (useful for larger teams or advanced multisite installations)

As for the default capability, the most common default capability for (plugin) settings is the `manage_options` capability (or `manage_network_options` for multisite, except if they allow some control to the users of a site in a network). But really, almost anything is better than the current `edit_plugins` capability. Feel free to change my PR. Oh, and you can also add the later removed filtering function to the wiki as an example for 3rd parties.

**Comment by spvickers** [comment]
Thanks for your contribution - looks most sensible.

**Comment by zigasancin** [comment]
@spvickers Thanks for further optimizing the PR (I usually use a more modular / flexible approach, but I don't think that there will be a need for filtering each submenu page). Do you plan to merge the PR and release a minor version of the plugin in the near future?

**Comment by spvickers** [comment]
Thanks for reporting this poor code; a change has now been committed to rectify it.
