### ISSUE TITLE
Library to tool compatibility?

### ISSUE THREAD

**Issue by HaakonME** [celtic-project/wordpress-lti#25]
I am stuck on Wordpress 5.7.11 at the moment, and installed the Wordpress LTI plugin, then found I cannot use it, as it requires the ceLTIc LTI Library plugin as well, but the library plugin version is incompatible with my version of Wordpress. 

Is there an earlier version of the library I can use?

Is there some file I may tinker with to make it work with my version of Wordpress?

Cheers,
Haakon

**Comment by spvickers** [comment]
If you are not using PHP 8.1 (or higher), then I believe version 4.10.3 (or earlier) of the ceLTIc-LTI Library plugin should work with your version of WordPress.

**Comment by HaakonME** [comment]
Thank you, I will check it out!
