### ISSUE TITLE
Usecase Question: Non-multi-site WP instance, readonly access, using only for SSO?

### ISSUE THREAD

**Issue by syntaxseed** [celtic-project/wordpress-lti#26]
Hi,
Great looking plugin! Been learning about the LTI spec from scratch for a new client.

We are building a WP site (non multisite) that is very close to a vanilla WP install. We will provide learning resources to logged in users. If you aren't logged in, you can't see site content.

Our client is a major media company with an education platform. They would like to connect their users (teachers) to our site using LTI as a Single Sign On method to log users into our WP site.

However we don't want to create new user records in our WP database when a user comes from the platform. Just perform the SSO handshake, populate a user session and their role and then allow them to access the site. We don't want the users to create posts or do anything on our WP site at all besides read content.

I've installed the LTI tool plugin and started configuring it and trying out the connection from the saLTIre platform mocking tool. But I'm getting the impression that

1. This plugin might be overkill for our needs.
2. This plugin doesn't allow us to prevent user records from being created in our DB (populate the session only).
3. Can't configure more than one 'role' for Instructors coming from the platform (to differentiate which groups of content on our site that the instructor can view).

Just wondering if anyone could provide guidance on my thoughts here, and if there is a more basic way to perform *only* the login handshake and session population ourselves?

I'm also getting a fatal error when trying to connect from the saLTIre platform mock... but I'm not sure I've configured everything properly yet. EDIT, tracked down the error and logged an issue #27.

Thanks so much!

**Comment by spvickers** [comment]
I am not sure that WordPress allows users to be authenticated to access its content without having a record in its user's database.  But if it does, then you could create a companion plugin which overrides the "onLaunch" behavior to set up the session as required (see, for example, the existing companion plugins for use with [Pressbooks](https://github.com/celtic-project/Pressbooks-lti-tool/) and [LearnDash](https://github.com/celtic-project/lti-tool-learndash)).

**Comment by syntaxseed** [comment]
Hmm interesting! Thanks!
