### ISSUE TITLE
Request failed: Missing Custom Parameter 

### ISSUE THREAD

**Issue by csmith-tcs** [celtic-project/wordpress-lti#28]
I have connected an LTI Platform (Canvas) to the LTI Connector. When I launch the activity from canvas it redirects back to canvas with the error message in the url being "assignments?lti_errormsg=Sorry%2C+there+was+an+error+connecting+you+to+the+application.&lti_errorlog=Debug+error%3A+Missing+custom+parameter"

From Error Log
[ERROR] Request failed with reason: 'Missing custom parameter'
See: 
  /home/erautcsi/public_html/wp-content/plugins/celtic-lti/vendor/celtic/lti/src/Util.php line 213
  /home/erautcsi/public_html/wp-content/plugins/celtic-lti/vendor/celtic/lti/src/Tool.php line 487
  /home/erautcsi/public_html/wp-content/plugins/lti-tool/lti-tool.php line 248
  /home/erautcsi/public_html/wp-includes/class-wp-hook.php line 324
  /home/erautcsi/public_html/wp-includes/class-wp-hook.php line 348
  /home/erautcsi/public_html/wp-includes/plugin.php line 565
  /home/erautcsi/public_html/wp-includes/class-wp.php line 418
  /home/erautcsi/public_html/wp-includes/class-wp.php line 813
  /home/erautcsi/public_html/wp-includes/functions.php line 1336
  /home/erautcsi/public_html/wp-blog-header.php line 16
  /home/erautcsi/public_html/index.php line 17
  
  Index.php line 17 require __DIR__ . '/wp-blog-header.php';

**Comment by spvickers** [comment]
I suspect you also have the lti-tool-learndash plugin installed which expects a custom parameter to specify the LearnDash course to be accessed.

**Comment by csmith-tcs** [comment]
I do have the lti-tool-learndash installed how would i check to see what is expected?

**Comment by spvickers** [comment]
Have you checked the documentation?  Especially the Usage page at https://github.com/celtic-project/lti-tool-learndash/wiki/Usage

**Comment by csmith-tcs** [comment]
It was not setup properly on the Canvas side of the application. Thank you for the assistance on that.
