### ISSUE TITLE
WP 5.2.4 Installation issue

### ISSUE THREAD

**Issue by roodsy** [celtic-project/wordpress-lti#4]
Hi Guys,

Has anyone managed to get the plugin to load correctly in WordPress 5.2.4.

I tried on a customers site and into a vanilla clean install of WP 5.2.4 with no other plugins. The plugin installs without error but the tool isn't loaded into the admin dashboard.

Was wondering if anyone had a patch/fix before I start digging in and single stepping it.

**Comment by spvickers** [comment]
I have updated my evaluation site to 5.2.4 and the LTI Tool Consumers plugin is still visible and accessible on the Network Admin page.

**Comment by roodsy** [comment]
Thanks for the quick response.

Yep sorry the issue was PBKAC (Problem Between Keyboard And Chair). I had not setup multi-site on either deployment. Is there an easy way to deploy on a single site or am I just going to need to dig through the plugin and make the changes myself to support this style of deployment?

**Comment by roodsy** [comment]
Sorry about the newbie question. It's my first look at WP and plugins. I have resolved this myself so you can close off the thread if you want
